services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: perylothdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app-service:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/perylothdb
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: perylothdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  pg_data: